project_id = "dyqhrwvjnosqhaslbmwr"

[functions.detect-disease]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = true

[functions.get-weather]
verify_jwt = true

[functions.predict-yield]
verify_jwt = true
